# -*- coding: utf-8 -*-
"""AT2 - AD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRzWkwqWJqkJAupRMT8d4TBQcb7Wl10E
"""

taxas_analfabetismo = {
    'Alagoas': '17,2%',
    'Piaí': '16,6%',
    'Maranhão': '16,3%',
    'Paraíba': '16,1%',
    'Sergipe': '13,9%',
    'Ceará': '13,3%',
    'Rio Grande do Norte': '12,9%',
    'Bahia':'12,7%',
    'Acre': '12,1%',
    'Pernambuco' : '11,9%',
    'Tocantins': '10%',
    'Pará': '8,8%',
    'Mato Grosso': '7,1%',
    'Rondônia': '6,5%',
    'Amapá': '6,1%',
    'Roraima':'6%',
    'Minas Gerais': '5,8%',
    'Amazonas': '5,8%',
    'Goiás': '5,7%',
    'Espírito Santo': '5,5%',
    'Paraná': '5%',
    'Mato Grosso do Sul': '5%',
    'Distrito Federal': '3,1%',
    'Rio Grande do Sul':'3%',
    'São Paulo':'2,6%',
    'Santa Catarina':'2,5%',
    'Rio de Janeiro':'2,4%',

}
estado = input('Digite o estado brasileiro que você deseja verificar a taxa de analfabetismo:')
print("A taxa de analfabetismo do estado de", estado, "é:", taxas_analfabetismo[estado])